# Generated by Django 3.1.2 on 2023-05-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230522_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=80)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
    ]
