# Generated by Django 3.1.2 on 2023-05-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='vigente',
        ),
    ]
